// Poster-frame generator. Hand-run:  node tools/poster.mjs
// Renders each configured instrument state to a committed SVG (figures/) and
// injects it into its page between <!-- poster:KEY --> markers, idempotently.
// The posters are the archival layer: with JS off (or dead, in 2041) the pages
// still teach, print, and index.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import * as fitScatter from '../js/instruments/fit-scatter.mjs';
import * as lossBowl from '../js/instruments/loss-bowl.mjs';
import { synthLine, ols } from '../js/math/core.mjs';

export function injectPoster(html, key, svg) {
  const re = new RegExp(`<!-- poster:${key} -->[\\s\\S]*?<!-- /poster:${key} -->`);
  if (!re.test(html)) throw new Error(`marker not found: poster:${key}`);
  return html.replace(re, `<!-- poster:${key} -->\n${svg}\n<!-- /poster:${key} -->`);
}

const root = new URL('..', import.meta.url);
const inRepo = p => new URL(p, root);

function synState() {
  const d = synthLine({ seed: 11, n: 12, slope: 0.62, intercept: 1.1, noise: 0.9 });
  return d;
}

const CONFIGS = [{
  file: 'least-squares.html',
  posters: [
    {
      key: 'fit-scatter-synthetic', instrument: fitScatter,
      state: () => {
        const d = synState();
        // deliberately wrong line: the poster should show fat, countable squares
        return { ...fitScatter.defaults, idKey: 'fs-syn', xs: d.xs, ys: d.ys, truth: d.truth, slope: 0.15, intercept: 3.2 };
      },
    },
    {
      key: 'loss-bowl-synthetic', instrument: lossBowl,
      state: () => {
        const d = synState();
        return { ...lossBowl.defaults, idKey: 'lb-syn', xs: d.xs, ys: d.ys, slope: 0.15, intercept: 3.2, loss: 'squared' };
      },
    },
    {
      key: 'fit-scatter-births', instrument: fitScatter,
      state: () => {
        let b;
        try {
          b = JSON.parse(readFileSync(inRepo('data/births.json'), 'utf8'));
        } catch {
          // offline fallback: labeled placeholder, never a silent substitution
          console.error('warning: data/births.json missing — births poster uses a labeled placeholder');
          const d = synthLine({ seed: 99, n: 60, slope: 190, intercept: -3600, noise: 420, xMin: 30, xMax: 42 });
          return { ...fitScatter.defaults, idKey: 'fs-births', xs: d.xs, ys: d.ys, residuals: false,
            ...ols(d.xs, d.ys),
            labels: { x: 'gestational age (weeks)', y: 'birthweight (g)', title: 'placeholder — real data pending' } };
        }
        const fit = ols(b.xs, b.ys);
        return { ...fitScatter.defaults, idKey: 'fs-births', xs: b.xs, ys: b.ys, residuals: false,
          slope: fit.slope, intercept: fit.intercept,
          labels: { x: 'gestational age (weeks)', y: 'birthweight (g)', title: 'every birth is a point. the line is a choice.' } };
      },
    },
  ],
}];

function main() {
  mkdirSync(inRepo('figures/'), { recursive: true });
  for (const cfg of CONFIGS) {
    const pagePath = inRepo(cfg.file);
    let html = readFileSync(pagePath, 'utf8');
    for (const p of cfg.posters) {
      const svg = `<!-- generated by tools/poster.mjs -->\n${p.instrument.render(p.state())}`;
      writeFileSync(inRepo(`figures/${p.key}.svg`), svg + '\n');
      html = injectPoster(html, p.key, svg);
      console.log(`poster: ${p.key} -> figures/${p.key}.svg + ${cfg.file}`);
    }
    writeFileSync(pagePath, html);
  }
}

if (process.argv[1] && import.meta.url.endsWith(process.argv[1].replace(/\\/g, '/').split('/').pop())) {
  main();
}
